### ISSUE TITLE
Request: File size in the preview window!

### ISSUE THREAD

**Issue by jamescooper-gd** [AncientRoman/SublimeOpenFileOverSSH#7]
It's great to see the files in a folder, but I accidentally opened a 2.8Gb file and it killed sublime.  Any chance the file size could be included in the preview please?

**Comment by AncientRoman** [comment]
I like this idea!

Because I want to only require the remote machine be POSIX compliant, this turns out to be more difficult than I would have thought. I'd also like to keep the file discovery to one round trip to avoid delays with slow internet connections (i.e. I can't grab the files with `ls` and then `wc -c` each one).
Note that _stat(2)_ is not posix, _wc(1)_ can't list directories, posix _find(1)_ is limited and I couldn't figure out a way to have it list file names with sizes, _du(1)_ is block based, and posix _xargs(1)_ doesn't support changing the delimiter (-0 or -d).

Something like this would work perfect if it weren't for posix [xargs](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/xargs.html) not allowing the NULL delimiter: `/bin/ls -1Lp | grep -v /$ | tr '\n' '\0' | xargs -0 wc -c && /bin/ls -1Lp | grep /$`. This is `ls -1` stripped of directories, passed into `wc -c` by changing newlines into NULL and `xargs -0`, and concatenated with `ls -1` stripped of non-directories. 

It seems to me this really only leaves parsing `ls -l` (despite [common convention](https://unix.stackexchange.com/questions/128985/why-not-parse-ls-and-what-to-do-instead)) using `-1go` and `LC_TIME=POSIX` to make the output more standardized. See the POSIX `ls` man page [here](https://pubs.opengroup.org/onlinepubs/009695399/utilities/ls.html).

If you have any ideas, I'm all ears. Do you have a solution in mind?

**Comment by jamescooper-gd** [comment]
Not my area of expertise I'm afraid, but can you use awk?

`ls -Fgho | awk '{print $3, $7}'`

Edit - sorry, I didn't read the "don't parse ls" comment..

**Comment by AncientRoman** [comment]
Fair enough. But yeah, I think that's pretty much what I'm going to do.
Time to parse some ls 🤙
